apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksebs-deployment
  labels:
    app: eksebs
spec:
  selector:
    matchLabels:
      app: eksebs
  template:
    metadata:
      labels:
        app: eksebs
    spec:
      containers:
      - name: web
        image: 094033154904.dkr.ecr.eu-west-1.amazonaws.com/pythonhelloworld
        ports:
        - containerPort: 8080
